version: "3.8"
services:
  app:
    container_name: app
    extra_hosts:
     - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    ports:
       - '${APP_PORT:-80}:80'
    expose:
      - 9000
    volumes:
      - .:/var/www/html
    networks:
      - my_network

  database:
    container_name: database
    image: mysql:8
    restart: unless-stopped
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: panda
      MYSQL_DATABASE: panda
      MYSQL_USER: panda
      MYSQL_PASSWORD: panda
    networks:
      - my_network

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html/public
    depends_on:
      - app
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  mysql: